name: 'Build osx target for release'

on:
  push


jobs:
  release:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v2
      
      - run: ls /usr/local/opt/llvm/lib
      - run: ls /usr/local/lib
      - run: ls /usr/lib
